stages:
    - deploy

execute_job:
    stage: deploy
    tags:
        - ansible
    script:
        - 'echo $VAULT_PASS > .vault_pass.txt'
        - 'ansible-playbook playbook.yml -u root --vault-password-file .vault_pass.txt'
        - 'rm .vault_pass.txt'

    only:
        refs:
            - master

    when: manual
